### ISSUE TITLE
permissions on sample files?

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#43] opened 2019-06-12 20:33 UTC
$ /usr/local/opt/rnastructviz/share/RNAStructViz/ERROR: Opening file "/usr/local/opt/rnastructviz/share/RNAStructViz/sample_structures/C.elegans_GTfold_16S.dot" : Permission denied
[1]+  Segmentation fault: 11  /usr/local/opt/rnastructviz/bin/RNAStructViz

Note that the ct files (like C.elegans_GTfold_16S.ct) opened fine, so it's a file problem not a directory problem.

**Comment by ceheitsch** [comment] 2019-06-12 20:35
Noting that file content is visible in RNAStructViz viewer (right frame of file loader window).

**Comment by ceheitsch** [comment] 2019-06-12 20:36
Appears to be the same problem: 
$ /usr/local/opt/rnastructviz/bin/RNAStructViz
ERROR: Opening file "/usr/local/opt/rnastructviz/share/RNAStructViz/sample_structures/helix_format_sample.helix" : Permission denied
Segmentation fault: 11

**Comment by maxieds** [comment] 2019-06-12 21:37
@ceheitsch I was not able to reproduce your error on the remote Mac OSX box, nor on Linux. The [first run instructions]() suggest that you copy the sample structure files into your home directory. I did also change the Makefile on the most recent version of *RNAStructViz* (v1.6.5-testing) to chmod those files to permissions of *555*, which might make a difference on your system. Please reinstall StructViz and try again to see if the problem persists.

**Comment by maxieds** [comment] 2019-06-29 04:23
@ceheitsch Can you please respond to the previous message? So we can get this issue handled and on the closed list?

**Comment by ceheitsch** [comment] 2019-07-01 19:41
@maxieds Same problem with C.elegans_GTfold_16S.dot file even when sample_structures is copied to home directory.  The file can be edited in vi, so unclear why RNAStructViz won't load it.

**Comment by ceheitsch** [comment] 2019-07-01 19:45
@maxieds Confirming that RNAStructViz (v1.6.5-testing) was reinstalled prior to testing.  There are no differences in the permissions of the files on the command line.  The *.dot file preview correctly appears in the small window.  It is only when actually loading the file that the error message (documented above) appears.

**Comment by maxieds** [comment] 2019-07-11 11:00
@ceheitsch Please test out the new permissions on the installed files with version *v1.6.6-testing*. The updated brew package for this version is now posted. You will need to reinstall to test the changes. I for some reason cannot get the VNC client to work over the slow house wifi connection, so I am not able to test it myself at the moment.

**Comment by ceheitsch** [comment] 2019-07-11 21:02
Followed reinstall instructions on wiki.  Resulted in:
> Error: Directory not empty @ dir_s_rmdir - /usr/local/Cellar/rnastructviz/v1.6.6-testing_1
Installed version is still v1.6.5-testing and it's unlikely that I will have time to circle back to this until next week.

**Comment by maxieds** [comment] 2019-07-14 02:11
This is fixed in the latest release. The sample structures directory files are now copied with the brew script installer, which leads to correct (and tested) permissions.

**Closed by maxieds** 2019-07-14 02:11 UTC
