### ISSUE TITLE
Mac OS load files browser bottom widget sometimes does not display correctly

### ISSUE THREAD

**Issue by maxieds** [gtDMMB/RNAStructViz#89] opened 2020-02-08 01:36 UTC
# Demonstration of the problem (active bug)

This error has been noticed on multiple Mac machine installs, but we have so far yet to be able to reproduce the bug exactly. After using RNAStructViz for a while, sometimes, when clicking on "*Load Files*" to open more structures, the bottom widget fails to display correctly. As in:

![Screen Shot 2020-02-07 at 8 22 18 PM](https://user-images.githubusercontent.com/22165688/74076765-6a20db80-49e8-11ea-8e5f-b1603a83a2f3.png)

The correct display actually looks like the following:

![Screen Shot 2020-02-07 at 8 29 22 PM](https://user-images.githubusercontent.com/22165688/74076786-8c1a5e00-49e8-11ea-92c3-a9d94d44106d.png)

# Suggestions of causes for the display issue:

* Loading and processing plots with the *StatsWindow*, followed by trying to open the *Load Files* dialog after closing that window? 
* The following message gets printed to the terminal / console when the error occurs: 
```bash
Fl_Text_Buffer::remove_modify_callback(): Can't find modify CB to remove
Fl_Text_Buffer::remove_predelete_callback(): Can't find pre-delete CB to remove
```
Any users that are able to accurately, i.e., predictably with steps, regenerate this issue with RNAStructViz, please follow up below and let me know so I can figure out a fix for the problem! 

# Proposed solutions in the meantime: 

In the meantime, whenever this happens, please just restart RNAStructViz again, or choose new structures to load without using the bottom widget in the dialog (less optimal solution).

**Comment by maxieds** [comment] 2020-03-03 07:15
@ceheitsch 
I believe that the issue has now been fixed after some good discussions on sources of the original error with the core FLTK developers today. Please upgrade to **v2.3.4-testing** to see the changes.

**Comment by ceheitsch** [comment] 2020-05-18 15:38
It's hard to verify the bug fix since we could never reliably reproduce it.  However, I've been working with RNAStructViz a lot recently, and not experienced this bug so will go ahead and close the issue.

**Closed by ceheitsch** 2020-05-18 15:38 UTC
Labels: Proposed fix in place >= v2.3.4-testing, 🍎 Mac OSX
